In [1]:
#TF_ENABLE_ONEDNN_OPTS
import os
import shutil

In [2]:
print(os.getenv('TF_ENABLE_ONEDNN_OPTS'))

None


In [3]:
os.environ['TF_ENABLE_ONEDNN_OPT'] = '0'

In [4]:
import tensorflow as tf
tf.__version__

'2.18.0'

In [5]:
import pandas as pd

### Initialization of Tensors

In [6]:
x = 10
print(x)

10


In [7]:
type(x)

int

In [8]:
x = tf.constant(10)
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [9]:
x = tf.constant(10, shape=(2, 2), dtype=tf.float32)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10., 10.],
       [10., 10.]], dtype=float32)>

In [10]:
x = tf.constant([10, 20, 30, 40], shape=(2, 2), dtype=tf.float32)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10., 20.],
       [30., 40.]], dtype=float32)>

In [11]:
x = tf.constant([10, 20, 30], shape=(1, 3), dtype=tf.float32)
x

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[10., 20., 30.]], dtype=float32)>

In [12]:
x = tf.constant([10, 20, 30], shape=(3, 1), dtype=tf.float32)
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[10.],
       [20.],
       [30.]], dtype=float32)>

In [13]:
x = tf.constant([[10, 20, 30], [40, 50, 60]], shape=(3, 2), dtype=tf.float32)
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10., 20.],
       [30., 40.],
       [50., 60.]], dtype=float32)>

In [14]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [15]:
tf.zeros((3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [16]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [17]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [18]:
tf.range(start=1, limit=20, delta=3)

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([ 1,  4,  7, 10, 13, 16, 19])>

In [19]:
tf.random.uniform((3,3), minval=0, maxval=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.84258413, 1.229398  , 2.5277889 ],
       [2.608574  , 2.8498297 , 2.0374112 ],
       [1.2857387 , 1.1092783 , 0.88241386]], dtype=float32)>

In [20]:
tf.random.normal((5,5), mean=0, stddev=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.1228492 ,  0.70208126,  0.28465763,  1.611014  ,  1.242054  ],
       [ 0.0257307 ,  0.79876775, -0.5315268 ,  2.649393  ,  0.29903817],
       [ 0.18381302, -1.2462215 ,  1.8715903 ,  1.361511  ,  1.6999632 ],
       [-0.5597735 , -0.9892848 ,  1.061752  ,  1.546001  , -0.4827515 ],
       [-2.4126956 , -0.2761537 ,  1.567401  ,  0.25301006,  1.582433  ]],
      dtype=float32)>

In [21]:
x = tf.range(10)

In [22]:
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [23]:
tf.cast(x, dtype=tf.float32)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

### Mathematical Operations

In [24]:
x = tf.constant(10)
y = tf.constant(20)

In [25]:
type(x)

tensorflow.python.framework.ops.EagerTensor

In [26]:
x + y

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [27]:
tf.add(x,y)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [28]:
tf.subtract(x,y)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [29]:
tf.multiply(x, y)

<tf.Tensor: shape=(), dtype=int32, numpy=200>

In [30]:
tf.divide(x, y)

<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

In [31]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

In [32]:
tf.matmul(x, y)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-1.310879  , -6.6444407 ,  1.8212175 , -1.530839  ],
       [ 0.49135917, -1.690857  , -1.6178322 , -1.1011473 ]],
      dtype=float32)>

In [33]:
x @ y #Same as above

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-1.310879  , -6.6444407 ,  1.8212175 , -1.530839  ],
       [ 0.49135917, -1.690857  , -1.6178322 , -1.1011473 ]],
      dtype=float32)>

### Index

In [34]:
x = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [35]:
x[2]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [36]:
x[2:5]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 5])>

In [37]:
x[:]

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

In [38]:
x[2:]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 3,  4,  5,  6,  7,  8,  9, 10])>

In [39]:
x[:6]

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [40]:
x[::2]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [41]:
tf.gather(x, [0, 3, 7])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 8])>

In [42]:
x = tf.constant([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [43]:
x[0,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [44]:
x[0:2, :]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [45]:
x[0, : 1:2]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1])>

In [46]:
x[:, 1:3]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6],
       [8, 9]])>

In [47]:
x[0:2, 0:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]])>

### Reshaping

In [48]:
x = tf.range(10)

In [49]:
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [53]:
tf.reshape(x, (5, 2))

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])>